<a href="https://colab.research.google.com/github/jiorjioo/KelasMahir-3.0/blob/main/Balma_Bahira_Pilkada_DKI_BoW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pembersihan Data

**Import library dan package yang dibutuhkan**

In [60]:
import sys

if not sys.warnoptions:
    import warnings
    warnings.simplefilter("ignore")

In [61]:
import numpy as np
import pandas as pd
import string

**Masukkan dataset yang akan digunakan**

In [62]:
twit_sentimen = pd.read_csv('https://raw.githubusercontent.com/jiorjioo/treasure/main/dataset_tweet_sentiment_pilkada_DKI_2017.xls.csv', sep=',', encoding = 'utf-8')
twit_sentimen.head()


Id  ...                                         Text_Tweet
0   1  ...  Banyak akun kloning seolah2 pendukung #agussil...
1   2  ...  #agussilvy bicara apa kasihan yaa...lap itu ai...
2   3  ...  Kalau aku sih gak nunggu hasil akhir QC tp lag...
3   4  ...  Kasian oh kasian dengan peluru 1milyar untuk t...
4   5  ...  Maaf ya pendukung #AgusSilvy..hayo dukung #Ani...

[5 rows x 4 columns]

kolom yang kita punya: **ID, Sentiment, Pasangan_Calon, Text_Tweet**

In [91]:
tweet = twit_sentimen.Text_Tweet
paslon = twit_sentimen.Pasangan_Calon
sentimen = twit_sentimen.Sentiment

tweet

0      Banyak akun kloning seolah2 pendukung #agussil...
1      #agussilvy bicara apa kasihan yaa...lap itu ai...
2      Kalau aku sih gak nunggu hasil akhir QC tp lag...
3      Kasian oh kasian dengan peluru 1milyar untuk t...
4      Maaf ya pendukung #AgusSilvy..hayo dukung #Ani...
                             ...                        
895    Kali saja bpk @aniesbaswedan @sandiuno lihat, ...
896    Kita harus dapat merangkul semua orang tanpa b...
897    Ini jagoanku dibidang digital <Smiling Face Wi...
898                 #PesanBijak #OkeOce #GubernurGu3 ...
899    Sandiaga: Bangun Rumah DP 0% Lebih Simpel Diba...
Name: Text_Tweet, Length: 900, dtype: object

**MULAI TEXT PROCESSING**

**Proses Case Folding**

In [92]:
# CASE FOLDING

import re, string, unicodedata 

def Case_Folding(text):
    # Hapus non-ascii
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')
    
    # Menghapus Tanda Baca
    text = re.sub(r'[^\w]|_',' ', text)
    
    # Menghapus Angka
    text = re.sub("\S*\d\S*", "", text).strip()
    text = re.sub(r"\b\d+\b", " ", text)
    
    # Mengubah text menjadi lowercase
    text = text.lower()
    
    # Menghapus white space
    text = re.sub('[\s]+', ' ', text)
    
    return text

**Proses Lemmatization**

In [ ]:
!pip install nlp-id

In [66]:
from nlp_id.lemmatizer import Lemmatizer 
lemmatizer = Lemmatizer() 
print(tweet[11])
tweet[11]=lemmatizer.lemmatize(tweet[11]) 
tweet[11]

Batal nyoblos, baru tau ternyata ga ada no.1 di kertas suara. #AHY #kangen #mosing	


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


'batal nyoblos baru tau nyata ga ada no 1 di kertas suara ahy kangen mosing'

**Proses Stemming**

In [67]:
!pip install PySastrawi

In [68]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Membuat stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()
print(tweet[12])

tweet[12] = stemmer.stem(tweet[12])
tweet[12]

sudah boleh Ngakak? survey mu jauh panggang dari api ! #Ahy


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


'sudah boleh ngakak survey mu jauh panggang dari api ahy'

**Proses Memfilter Slang Words**

In [69]:
slang_dictionary = pd.read_csv('https://raw.githubusercontent.com/nikovs/data-science-portfolio/master/topic%20modelling/colloquial-indonesian-lexicon.csv')
slang_dict = pd.Series(slang_dictionary['formal'].values,index=slang_dictionary['slang']).to_dict()

In [70]:
def Slangwords(text):
    for word in text.split():
        if word in slang_dict.keys():
            text = text.replace(word, slang_dict[word])
    return text

In [71]:
print(tweet[10])

tweet[10] = Slangwords(tweet[10])
tweet[10]

dammnn,!! politik cantik #SBY ngorbanin #AHY


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


'dammnn,!! politik cantik #SBY mengorbankan #AHY'

**Proses Stopword**

In [72]:
from nlp_id.stopword import StopWord 
stopword = StopWord() 

In [73]:
from nlp_id.stopword import StopWord 
print(tweet[340])

tweet[340]=stopword.remove_stopword(tweet[340])
tweet[340]

Kafirrrrrr dan menista ya??!#SaveAhok #RIPJUSTICEINDONESIA #Ahok #AhokDjarot — iqra, iqra, iqra !!! http://www.nu.or.id


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


'Kafirrrrrr menista??!#SaveAhok#RIPJUSTICEINDONESIA#Ahok#AhokDjarot— iqra, iqra, iqra!!! http://www. nu. or. id'

**Testing Menerapkan ke Semua Langkah**

In [93]:
twit_sentimen['content_processed'] = ''

for i, row in twit_sentimen.iterrows():
  content = tweet[i]
  result = Case_Folding(content)
  result = lemmatizer.lemmatize(result)
  result = stemmer.stem(result)
  result = Slangwords(result)
  result = stopword.remove_stopword(result)
  twit_sentimen['content_processed'][i] = result

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


In [97]:
twit_bersih = twit_sentimen[['Sentiment', 'Pasangan_Calon', 'content_processed']]
twit_bersih

Sentiment Pasangan_Calon                                  content_processed
0    negative     Agus-Sylvi  akun kloning dukung agussilvy serang paslon an...
1    negative     Agus-Sylvi     agussilvy bicara kasihan lap air mata wkwkwkwk
2    negative     Agus-Sylvi  enggak memenunggu hasil qc memenunggu motif cu...
3    negative     Agus-Sylvi  kasihh oh kasihh peluru rw agussilvy mempan me...
4    negative     Agus-Sylvi  maaf dukung agussilvy hayo dukung aniessandi p...
..        ...            ...                                                ...
895  positive    Anies-Sandi  bpk aniesbaswedan sandiuno lihat rspun selfie ...
896  positive    Anies-Sandi  rangkul orang batas usia kelamin okeoce ok han...
897  positive    Anies-Sandi  jago bidang digital smiling face with sunglass...
898  positive    Anies-Sandi                                  pesanbijak okeoce
899  positive    Anies-Sandi  sandiaga bangun rumah dp simpel banding tol ci...

[900 rows x 3 columns]

In [ ]:
twit_bersih.to_csv('twit_bersih.csv', index = False)
clean_tweet = pd.read_csv('twit_bersih.csv', encoding = 'latin1')
clean_tweet.head()

##Try BoW

**Note: INGAT INGAT NAMA DATASET YANG BAKAL DIPAKE DI BoW = CLEAN_TWEET**

In [99]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [101]:
kosa_kata = set()
for i in clean_tweet.content_processed:
    token_kal=set(word_tokenize(i.lower()))
    kosa_kata=set.union(kosa_kata,token_kal)
    #print(kosa_kata)
    
kosa_kata = sorted(kosa_kata)
print(kosa_kata)

# Jumlah kata-kata pada list vocab           
jumlah_kosa_kata = len(kosa_kata)
print(jumlah_kosa_kata)

['a', 'aa', 'aagym', 'abaaah', 'abal', 'abang', 'abdi', 'absurd', 'abunawas', 'aburizal', 'abused', 'acara', 'acu', 'adaaqua', 'adalahkita', 'addiems', 'adekku', 'adil', 'adjierimbawan', 'adjrot', 'agam', 'agama', 'agllusylludhoyono', 'agus', 'agusharimurtiyudhoyono', 'agussilvy', 'agussylvi', 'agusyudhoyono', 'ah', 'aher', 'ahli', 'ahmadfuadanwar', 'ahok', 'ahokbtp', 'ahokdicintairakyat', 'ahokdjarot', 'ahokdjarota', 'ahokdjarotdirosi', 'ahokdjarotlebihbaik', 'ahokdjarotmenang', 'ahoker', 'ahokers', 'ahokfornobel', 'ahokfree', 'ahokhebat', 'ahokishope', 'ahokjarot', 'ahokkalah', 'ahokkeok', 'ahoklovers', 'ahokmandikembang', 'ahokmartir', 'ahokmenang', 'ahokpanikahokkalah', 'ahokpenistaagama', 'ahokrekormuri', 'ahokselaludihati', 'ahokshow', 'ahoktakbersalah', 'ahoktumbang', 'ahox', 'ahy', 'ahya', 'ahyaforall', 'ahyahargamati', 'ahycenter', 'ahyfansclub', 'ahyforall', 'ahylovers', 'ahymaininsara', 'ahysylvi', 'aib', 'aiman', 'air', 'ajak', 'ajang', 'ajar', 'aji', 'ajibarang', 'aka', 'a

**Proses Membuat Dictionary Kosa Kata**

In [102]:
# BUAT DICT KOSA KATA UNTUK MEMBUAT BARIS KOSA KATA

indeks_kata = {}
for kata in kosa_kata:
    indeks_kata[kata] = 0
    
print(indeks_kata)

{'a': 0, 'aa': 0, 'aagym': 0, 'abaaah': 0, 'abal': 0, 'abang': 0, 'abdi': 0, 'absurd': 0, 'abunawas': 0, 'aburizal': 0, 'abused': 0, 'acara': 0, 'acu': 0, 'adaaqua': 0, 'adalahkita': 0, 'addiems': 0, 'adekku': 0, 'adil': 0, 'adjierimbawan': 0, 'adjrot': 0, 'agam': 0, 'agama': 0, 'agllusylludhoyono': 0, 'agus': 0, 'agusharimurtiyudhoyono': 0, 'agussilvy': 0, 'agussylvi': 0, 'agusyudhoyono': 0, 'ah': 0, 'aher': 0, 'ahli': 0, 'ahmadfuadanwar': 0, 'ahok': 0, 'ahokbtp': 0, 'ahokdicintairakyat': 0, 'ahokdjarot': 0, 'ahokdjarota': 0, 'ahokdjarotdirosi': 0, 'ahokdjarotlebihbaik': 0, 'ahokdjarotmenang': 0, 'ahoker': 0, 'ahokers': 0, 'ahokfornobel': 0, 'ahokfree': 0, 'ahokhebat': 0, 'ahokishope': 0, 'ahokjarot': 0, 'ahokkalah': 0, 'ahokkeok': 0, 'ahoklovers': 0, 'ahokmandikembang': 0, 'ahokmartir': 0, 'ahokmenang': 0, 'ahokpanikahokkalah': 0, 'ahokpenistaagama': 0, 'ahokrekormuri': 0, 'ahokselaludihati': 0, 'ahokshow': 0, 'ahoktakbersalah': 0, 'ahoktumbang': 0, 'ahox': 0, 'ahy': 0, 'ahya': 0, 'a

**Proses Membuat Matriks Kata**

In [104]:
# BUAT MATRIKS KATA

vektor_kata=np.array([])
for baris_teks in clean_tweet.content_processed:
    print(baris_teks)
    baris_kata = indeks_kata.copy()
    print('baris_kata', baris_kata)
    for kata in baris_teks.lower().split():
        baris_kata[kata]=+1
        print(baris_kata)
    baris_kata = np.array(list(baris_kata.values()))  
    vektor_kata = np.concatenate((vektor_kata,baris_kata), axis=0)
    print(vektor_kata)
matriks_kata = vektor_kata.reshape(twit_sentimen.shape[0], jumlah_kosa_kata)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[0. 0. 0. ... 0. 0. 0.]
jago bidang digital smiling face with sunglasses ok hand thonyleong com okeoce salambersama
baris_kata {'a': 0, 'aa': 0, 'aagym': 0, 'abaaah': 0, 'abal': 0, 'abang': 0, 'abdi': 0, 'absurd': 0, 'abunawas': 0, 'aburizal': 0, 'abused': 0, 'acara': 0, 'acu': 0, 'adaaqua': 0, 'adalahkita': 0, 'addiems': 0, 'adekku': 0, 'adil': 0, 'adjierimbawan': 0, 'adjrot': 0, 'agam': 0, 'agama': 0, 'agllusylludhoyono': 0, 'agus': 0, 'agusharimurtiyudhoyono': 0, 'agussilvy': 0, 'agussylvi': 0, 'agusyudhoyono': 0, 'ah': 0, 'aher': 0, 'ahli': 0, 'ahmadfuadanwar': 0, 'ahok': 0, 'ahokbtp': 0, 'ahokdicintairakyat': 0, 'ahokdjarot': 0, 'ahokdjarota': 0, 'ahokdjarotdirosi': 0, 'ahokdjarotlebihbaik': 0, 'ahokdjarotmenang': 0, 'ahoker': 0, 'ahokers': 0, 'ahokfornobel': 0, 'ahokfree': 0, 'ahokhebat': 0, 'ahokishope': 0, 'ahokjarot': 0, 'ahokkalah': 0, 'ahokkeok': 0, 'ahoklovers': 0, 'ahokmandikembang': 0, 'ahokmartir': 0, 'ahokmenang': 0, 'ahokpanikahokkalah': 0, 'ahokpenistaagama': 0, 'ahok

In [105]:
print(matriks_kata)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


**Membuat Data Frame Bag of Words**

In [106]:
# MEMBUAT DATA FRAME BAG OF WORDS

df_BoW = pd.DataFrame(matriks_kata, columns=kosa_kata, index=clean_tweet.content_processed.tolist())
df_BoW = df_BoW.astype('int')
df_BoW

a  aa  ...  zipper  zona
akun kloning dukung agussilvy serang paslon ani...  0   0  ...       0     0
agussilvy bicara kasihan lap air mata wkwkwkwk      0   0  ...       0     0
enggak memenunggu hasil qc memenunggu motif cui...  0   0  ...       0     0
kasihh oh kasihh peluru rw agussilvy mempan men...  0   0  ...       0     0
maaf dukung agussilvy hayo dukung aniessandi pu...  0   0  ...       0     0
...                                                ..  ..  ...     ...   ...
bpk aniesbaswedan sandiuno lihat rspun selfie o...  0   0  ...       0     0
rangkul orang batas usia kelamin okeoce ok hand...  0   0  ...       0     0
jago bidang digital smiling face with sunglasse...  0   0  ...       0     0
pesanbijak okeoce                                   0   0  ...       0     0
sandiaga bangun rumah dp simpel banding tol cip...  0   0  ...       0     0

[900 rows x 2503 columns]

**Membuat Fungsi Bag of Words()**

In [114]:
#Impor Modul Yang Diperlukan
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize

def Bag_Of_Words(clean_tweet):
    # Membuat list kosa kata dari seluruh teks input
    kosa_kata = set()
    for i in clean_tweet.content_processed:
        token_kal=set(word_tokenize(i.lower()))
        kosa_kata=set.union(kosa_kata,token_kal)
    kosa_kata = sorted(kosa_kata)
    # Membuat dictionary kata-kata
    indeks_kata = {}
    for kata in kosa_kata:
        indeks_kata[kata] = 0
    # Jumlah kosa kata(untuk kolom)
    jumlah_kosa_kata = len(kosa_kata)
    # Membagun matriks kata
    vektor_kata=np.array([])
    for baris_teks in clean_tweet.content_processed:
        baris_kata = indeks_kata.copy()
        for kata in baris_teks.lower().split():
            baris_kata[kata]=+1
        baris_kata = np.array(list(baris_kata.values()))  
        vektor_kata = np.concatenate((vektor_kata,baris_kata), axis=0)
    matriks_kata = vektor_kata.reshape(clean_tweet.shape[0], jumlah_kosa_kata)    
    df_bow = pd.DataFrame(matriks_kata, columns=kosa_kata, index=clean_tweet.content_processed.tolist())
    df_bow = df_bow.astype('int')
    return df_bow

**Implementasi BoW**

In [120]:
clean_tweet

In [122]:
df_BoW=Bag_Of_Words(clean_tweet)

# Export ke CSV
df_BoW.to_csv('dataset_bow.csv', index=False)

df_BoW

a  aa  ...  zipper  zona
akun kloning dukung agussilvy serang paslon ani...  0   0  ...       0     0
agussilvy bicara kasihan lap air mata wkwkwkwk      0   0  ...       0     0
enggak memenunggu hasil qc memenunggu motif cui...  0   0  ...       0     0
kasihh oh kasihh peluru rw agussilvy mempan men...  0   0  ...       0     0
maaf dukung agussilvy hayo dukung aniessandi pu...  0   0  ...       0     0
...                                                ..  ..  ...     ...   ...
bpk aniesbaswedan sandiuno lihat rspun selfie o...  0   0  ...       0     0
rangkul orang batas usia kelamin okeoce ok hand...  0   0  ...       0     0
jago bidang digital smiling face with sunglasse...  0   0  ...       0     0
pesanbijak okeoce                                   0   0  ...       0     0
sandiaga bangun rumah dp simpel banding tol cip...  0   0  ...       0     0

[900 rows x 2503 columns]